# Homework 1: Introduction to Machine Learning
Name: Esteban Martínez Camargo

# Q1. Pandas version

In [3]:
import pandas as pd
import numpy as np

pd.__version__

'3.0.6'

Getting the data

In [4]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

# Q2. Records count
How many records are in the dataset?

In [5]:
df.shape[0]

10000

# Q3. Fuel types

How many fuel types are presented in the dataset?

In [6]:
df["fuel_type"].nunique()

3

# Q4. Missing values

How many columns in the dataset have missing values?

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [34]:
print("Number of columns with missing values:", df.isna().any().sum())

Number of columns with missing values: 2

# Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [23]:
df_origin = df[['origin', "fuel_efficiency_mpg"]]
df_origin[df_origin["origin"] == "Asia"].describe().round(2)

       fuel_efficiency_mpg
count              2994.00
mean                 30.74
std                   2.84
min                  21.30
25%                  28.70
50%                  30.70
75%                  32.50
max                  41.20

In [35]:
max_fuel_efficiency_asia = df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()
print("Maximum fuel efficiency for Asia:", max_fuel_efficiency_asia)

Maximum fuel efficiency for Asia: 41.2

# Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

In [30]:
# Median before filling missing values
median_before = df["horsepower"].median()

# Most frequent horsepower value
most_frequent = df["horsepower"].mode()[0]

# Fill missing values and calculate the updated median
df_fillna = df["horsepower"].fillna(most_frequent)
median_after = df_fillna.median()

print("Median before: ", median_before)
print("Most frequent: ", most_frequent)
print("Median after: ", median_after)

Median before:  254.0
Most frequent:  252.0
Median after:  252.0

# Q7. Sum of weights

1.    Select all the cars from Asia
2.    Select only columns `vehicle_weight` and `model_year`
3.    Select the first 7 values
4.    Get the underlying NumPy array. Let's call it `X`.
5.    Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6.    Invert `XTX`.
7.    Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8.    Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9.    What's the sum of all the elements of the result?

In [33]:
X = (
    df.loc[df["origin"] == "Asia", ["vehicle_weight", "model_year"]]
    .head(7)
    .to_numpy()
)

XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv @ X.T @ y

print("Sum of all elements in w:", w.sum().round(3))

Sum of all elements in w: 0.369